repos:
-   repo: local
    hooks:
    -   id: generate-API-documenation
        name: generate-API-documenation
        entry: docs/generate_api_doc.sh
        language: script
        pass_filenames: false
-   repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-docstring-first
    -   id: check-merge-conflict
    -   id: name-tests-test
        args: ['--django']
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
