version: '3.1'

services:
  mongo:
    container_name: chronos_mongo
    image: mongo:4.4.0-bionic
    restart: always
    ports:
      - 27017:27017
    command: --replSet replica_set0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: local

  mongo-express:
    container_name: chronos_mongo-express
    image: mongo-express:0.54.0
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: local

  api:
    container_name: chronos_api
    restart: always
    ports:
      - 6000:80
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    command: /start-reload.sh
    environment:
      MODULE_NAME: src.chronos.api.main
    volumes:
      - ".:/chronos"
