[tool.poetry]
name = "chronos"
version = "0.1.0"
description = ""
authors = [
    "andrysiaczek <agata.and.11@gmail.com>",
    "Kuba Karmiński <kuba.karminski@bethink.pl>",
    "Miłosz Bednarzak <milosz.bednarzak@bethink.pl>"
]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
pandas = "^1.1.0"
datatosk = "^0.3.0"
python-dotenv = "^0.14.0"
tqdm = "^4.48.2"
pythink-toolbox = { git = "git@github.com:bethinkpl/pythink-toolbox.git", branch = "master"}
pandera = "^0.4.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.4.4"
pytest = "^6.0.1"
coverage = { version = "^5.1",  extras = ["toml"] }
hypothesis = { version = "^5.30.0",  extras = ["numpy", "pandas"] }
pytest-cov = "^2.10.1"
mypy = "^0.782"
nox = "^2020.5.24"
pre-commit = "^2.6.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
