name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Docker Compose
      run: docker-compose -f docker-compose-tests.yml up -d

    - name: Wait for MongoDB
      run: until docker exec test_mongo mongo -utest_user -ptest_pass --eval "print(\"Don't want to wait no longer!\")"; do sleep 1; done

    - name: Initiate Mongo replica sets
      run: docker exec test_mongo mongo -utest_user -ptest_pass --eval "rs.initiate()"

    - name: Run Nox-based CI
      run: docker exec chronos_tests poetry run cli ci
