version: '3.1'

services:
  test-mongo:
    container_name: test_mongo
    image: mongo:4.4.1-bionic
    restart: always
    ports:
      - 27018:27018
    command: --replSet replica_set0
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_pass
