# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install poetry
      uses: snok/install-poetry@v1.1.1
      with:
        version: 1.1.4
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependiencies
      run: poetry install

    - name: Build and publish
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: poetry publish --build -u$PYPI_USERNAME -p$PYPI_PASSWORD
